name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_DIR: ${{github.workspace}}/build
  VCPKG_ROOT: ${{github.workspace}}/third/vcpkg
  VCPKG_DEFAULT_BINARY_CACHE: ${{github.workspace}}/third/vcpkg/bincache

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            preset: windows-cl-x64-ninja
            triplet: x64-windows
          - os: ubuntu-latest
            preset: clang-x64-ninja
            triplet: x64-linux
          - os: macos-latest
            preset: clang-x64-ninja
            triplet: x64-osx

    steps:
    - name: "check out repo with vcpkg as submodule"
      uses: actions/checkout@v3
      with:
        # to use vcpkg as submodule
        submodules: recursive

    - name: "setup ninja"
      # TODO: review 
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: "Create directory '${{ env.VCPKG_DEFAULT_BINARY_CACHE }}'"
      run: mkdir -p $VCPKG_DEFAULT_BINARY_CACHE
      shell: bash

    - name: Cache/Restore vcpkg
      uses: actions/cache@v2
      with:
        path: |
          ${{ env.VCPKG_ROOT }}
          !${{ env.VCPKG_ROOT }}/buildtrees
          !${{ env.VCPKG_ROOT }}/packages
          !${{ env.VCPKG_ROOT }}/downloads
          !${{ env.VCPKG_ROOT }}/installed
        key: |
          ${{ runner.os }}-${{ matrix.triplet }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('vcpkg.json') }}-${{ hashFiles('.git/modules/third/vcpkg/HEAD') }}
        # CACHE_VERSION is used to clear cache explicitly

    - name: Add msbuild to PATH(Windows)
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v1.1

    - name: Configure build for amd64(Windows)
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - name: Add packages(Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libxmu-dev libxi-dev libgl-dev  # for glew
        sudo apt-get install -y libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev  # for glfw
        sudo apt-get install -y libgl1-mesa-dev
        sudo apt-get install -y mesa-utils freeglut3-dev
        # apt list | grep -i gl
        xvfb-run glxinfo | grep -i OpenGL


    - name: cmake configure
      run: |
        cmake --preset "${{matrix.preset}}"

    - name: cmake build
      run: |
        cmake --build --preset "${{matrix.preset}}-Debug"
        cmake --build --preset "${{matrix.preset}}-Release"

    # - name: Test
    #   run: ctest -C release
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: "artifacts_${{ runner.os }}"
        path: "build/${{matrix.preset}}/bin"

