name: MSBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIR: ${{github.workspace}}/build
  VCPKG_ROOT: ${{github.workspace}}/third/vcpkg
  VCPKG_DEFAULT_BINARY_CACHE: ${{github.workspace}}/third/vcpkg/bincache

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        # os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            platform: windows
            tool: vs2022
            build: Release
          # - os: ubuntu-latest
          #   platform: linux
          #   tool: clang
          #   build: Release
          # - os: macos-latest
          #   platform: osx
          #   tool: clang
          #   build: Release

    runs-on: ${{matrix.os}}

    steps:
    - name: "check out repo with vcpkg as submodule"
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: "Create directory '${{ env.VCPKG_DEFAULT_BINARY_CACHE }}'"
      run: mkdir -p $VCPKG_DEFAULT_BINARY_CACHE
      shell: bash

    - name: setup-msbuild
      if: contains(${{matrix.platform}}, 'windows')
      uses: microsoft/setup-msbuild@v1.1

    - name: cmake configure
      if: contains(${{matrix.platform}}, 'windows')
      shell: powershell
      run: |
        cmake --preset "${{matrix.platform}}-x64-${{matrix.tool}}" `
        	  ./

    - name: cmake build
      run: |
        cmake --build --preset "${{matrix.platform}}-x64-${{matrix.tool}}-${{matrix.build}}"

    # - name: Test
    #   run: ctest -C release
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts_win-x64
        path: "build/${{matrix.platform}}-x64-${{matrix.tool}}/bin/${{matrix.build}}"

