name: MSBuild
on:
  push:
    branches:
      - main
jobs:
  build:
    name: MSBuild
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: cmake
      shell: powershell
      run: |
        $msbuildPlatform = "x64"
        $buildDirectory = "build"
        mkdir $buildDirectory -Force -ErrorAction Stop | Out-Null
        cmake -G "Visual Studio 17 2022" `
              -A $msbuildPlatform `
              -B $buildDirectory `
              -D CMAKE_BUILD_TYPE=Release `
              -D BUILD_SHARED_LIBS=ON `
        	  ./

    - name: build
      run: |
        cd build
        msbuild cs.sln -t:rebuild -verbosity:diag -property:Configuration=Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts_win-x64
        path: build_${{matrix.arch}}/bin
 