name: MSBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIR: ${{github.workspace}}/build

jobs:
  build:
    strategy:
      matrix:
        platform: [windows, ]
        tool: [vs2022, ]
        build: [Release, Debug]

    runs-on: "${{matrix.platform}}-2022"

    env:
      BUILD_TYPE: ${{matrix.build}}
      CMAKE_PRESET: ${{matrix.build}}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: setup-msbuild
      if: contains(${{matrix.platform}}, 'windows')
      uses: microsoft/setup-msbuild@v1.1

    - name: cmake
      if: contains(${{matrix.platform}}, 'windows')
      shell: powershell
      run: |
        cmake --preset "${{matrix.platform}}-x64-${{matrix.tool}}" `
        	  ./

    - name: cmake build
      run: |
        cmake --build --preset "${{matrix.platform}}-x64-${{matrix.tool}}-${{matrix.build}}"

    # - name: Test
    #   run: ctest -C release
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts_win-x64
        path: "build/${{matrix.platform}}-x64-${{matrix.tool}}/bin/${{matrix.build}}"

