name: MSBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIR: ${{github.workspace}}/build

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: cmake
      shell: powershell
      run: |
        $msbuildPlatform = "x64"
        $buildDirectory = "build"
        mkdir $buildDirectory -Force -ErrorAction Stop | Out-Null
        cmake -G "Visual Studio 17 2022" `
              -A $msbuildPlatform `
              -B ${{env.BUILD_DIR}} `
              -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} `
              -D BUILD_SHARED_LIBS=ON `
        	  ./

    - name: build
      run: |
        msbuild ${{env.BUILD_DIR}}/cs.sln -t:rebuild -verbosity:diag -property:Configuration=Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts_win-x64
        path: build/bin/Release


 
