name: MSBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIR: ${{github.workspace}}/build

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-2022]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: cmake
      shell: powershell
      run: |
        cmake --preset "win-x64-vs2022" `
        	  ./


    - name: build
      run: |
        msbuild ${{env.BUILD_DIR}}/cs.sln -t:rebuild -verbosity:diag -property:Configuration=Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts_win-x64
        path: build/bin/Release


 
