name: MSBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIR: ${{github.workspace}}/build

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: setup-vcpkg
      uses: lukka/run-vcpkg@v10.0

    - name: vcpkg
      shell: powershell
      run: |
        echo ${env:VCPKG_ROOT}
        & ${env:VCPKG_ROOT}\vcpkg install
        & ${env:VCPKG_ROOT}\vcpkg integrate install
        & ${env:VCPKG_ROOT}\vcpkg list
        ls ${env:VCPKG_ROOT}\installed
    - name: cmake
      shell: powershell
      run: |
        cmake --preset  "win-x64-vs2022" `

              -D VCPKG_ROOT=${{env.VCPKG_ROOT}}`
        	  ./

    # - name: cmake
    #   shell: powershell
    #   run: |
    #     $msbuildPlatform = "x64"
    #     $buildDirectory = "build"
    #     mkdir $buildDirectory -Force -ErrorAction Stop | Out-Null
    #     cmake -G "Visual Studio 17 2022" `
    #           -A $msbuildPlatform `
    #           -B ${{env.BUILD_DIR}} `
    #           -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} `
    #           -D BUILD_SHARED_LIBS=ON `
    #           -D VCPKG_ROOT=${{env.VCPKG_ROOT}}`
    #     	  ./

    - name: build
      run: |
        msbuild ${{env.BUILD_DIR}}/cs.sln -t:rebuild -verbosity:diag -property:Configuration=Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts_win-x64
        path: build/bin/Release


 
